/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AdminController;
import Controller.BillController;
import Controller.CustomerController;
import Controller.ProfileController;
import Controller.StaffController;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Interface extends javax.swing.JFrame {
    
    // id cua nguoi dung
    int id_user;
    int totalprice=0;

    // loai tai khoan 0 =admin, 1 = staff
    boolean type;
    
    private String ImagePath;
    public Interface(int i, boolean t) {
        id_user = i;  type = t;
        initComponents();
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle("Home");
//        id_user = i;  type = t;
        reloadProfile();
        if (type){
//            adminBtn.setEnabled(false);
        } else {
//            staffBtn.setEnabled(false);
        }
    }
    StaffController stf = new StaffController();
    AdminController ad = new AdminController();
    private void reloadProfile(){
        if(!type){
            try {
                //admin
                ProfileController.getAdminInfoById(id_user, idInfo, nameInfo, phoneInfo, emailInfo,
                        addrInfo, shiftInfo, wdateInfo, hiLabel, addrLabel, shiftLabel, wdateLabel);
            } catch (SQLException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                ProfileController.getStaffInfoById(id_user, idInfo, nameInfo, phoneInfo, emailInfo, 
                        addrInfo, shiftInfo, wdateInfo, hiLabel);
            } catch (SQLException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JTabbedPane();
        profileTab = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        addrLabel = new javax.swing.JLabel();
        shiftLabel = new javax.swing.JLabel();
        wdateLabel = new javax.swing.JLabel();
        hiLabel = new javax.swing.JLabel();
        idInfo = new javax.swing.JLabel();
        nameInfo = new javax.swing.JLabel();
        phoneInfo = new javax.swing.JLabel();
        emailInfo = new javax.swing.JLabel();
        addrInfo = new javax.swing.JLabel();
        shiftInfo = new javax.swing.JLabel();
        wdateInfo = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();
        bookTab = new javax.swing.JPanel();
        billTab = new javax.swing.JPanel();
        CustomerIdLabel = new javax.swing.JLabel();
        CustomerId = new javax.swing.JTextField();
        Displayall = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        StaffId = new javax.swing.JTextField();
        IdBill = new javax.swing.JTextField();
        CreateBill = new javax.swing.JButton();
        AddDetailButton = new javax.swing.JButton();
        RemoveDetail = new javax.swing.JButton();
        reportTab = new javax.swing.JPanel();
        customerTab = new javax.swing.JPanel();
        cidLabel = new javax.swing.JLabel();
        cnameLabel = new javax.swing.JLabel();
        cphoneLabel = new javax.swing.JLabel();
        cmailLabel = new javax.swing.JLabel();
        caddrLabel = new javax.swing.JLabel();
        cregdateLabel = new javax.swing.JLabel();
        expdateLabel = new javax.swing.JLabel();
        membershipLabel = new javax.swing.JLabel();
        cnameField = new javax.swing.JTextField();
        cphoneField = new javax.swing.JTextField();
        cmailField = new javax.swing.JTextField();
        caddrField = new javax.swing.JTextField();
        cmembershipField = new javax.swing.JTextField();
        ccreateBtn = new javax.swing.JButton();
        cupdateBtn = new javax.swing.JButton();
        cremoveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        displayaBtn = new javax.swing.JButton();
        crdateField = new javax.swing.JLabel();
        cedateField = new javax.swing.JLabel();
        cidField = new javax.swing.JLabel();
        cSearchField = new javax.swing.JTextField();
        cSearchBox = new javax.swing.JComboBox<>();
        cSearchBtn = new javax.swing.JButton();
        staffTab = new javax.swing.JPanel();
        txtsearch_staff = new javax.swing.JTextField();
        ComboBox_search_staff = new javax.swing.JComboBox<>();
        Button_Search_staff = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Staff = new javax.swing.JTable();
        image_staff = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_staff = new javax.swing.JLabel();
        txtusername_staff = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpassword_staff = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtname_staff = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtphone_staff = new javax.swing.JTextField();
        txtemail_staff = new javax.swing.JTextField();
        txtaddress_staff = new javax.swing.JTextField();
        txtshift_count_staff = new javax.swing.JTextField();
        txtstartworkdate_staff = new javax.swing.JTextField();
        Button_Add_Staff = new javax.swing.JButton();
        Button_Update_staff = new javax.swing.JButton();
        Button_Delete_staff = new javax.swing.JButton();
        Button_New_Staff = new javax.swing.JButton();
        adminTab = new javax.swing.JPanel();
        txtsearch_admin = new javax.swing.JTextField();
        ComboBox_search_admin = new javax.swing.JComboBox<>();
        Button_Search_Admin = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_Admin = new javax.swing.JTable();
        Image_Admin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Label_ID_Admin = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUsername_Admin = new javax.swing.JTextField();
        txtPassword_Admin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtName_Admin = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPhone_Admin = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEmail_Admin = new javax.swing.JTextField();
        Button_Add_Admin = new javax.swing.JButton();
        Button_Update_Admin = new javax.swing.JButton();
        Button_New_Admin = new javax.swing.JButton();
        Button_Delete_Admin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        home.setBackground(new java.awt.Color(255, 255, 255));

        logoutBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutBtn.setText("Log out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idLabel.setText("ID:");

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText("Name:");

        phoneLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phoneLabel.setText("Phone:");

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailLabel.setText("Email:");

        addrLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addrLabel.setText("Address:");

        shiftLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        shiftLabel.setText("Shift count:");

        wdateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wdateLabel.setText("Start work date:");

        hiLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hiLabel.setText("Hello");

        idInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idInfo.setText("null");

        nameInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameInfo.setText("null");

        phoneInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneInfo.setText("null");

        emailInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailInfo.setText("null");

        addrInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addrInfo.setText("null");

        shiftInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        shiftInfo.setText("null");

        wdateInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wdateInfo.setText("null");

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profileTabLayout = new javax.swing.GroupLayout(profileTab);
        profileTab.setLayout(profileTabLayout);
        profileTabLayout.setHorizontalGroup(
            profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hiLabel)
                .addGap(213, 213, 213))
            .addGroup(profileTabLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(profileTabLayout.createSequentialGroup()
                        .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLabel)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel)
                            .addComponent(phoneLabel)
                            .addComponent(emailLabel)
                            .addComponent(addrLabel)
                            .addComponent(shiftLabel)
                            .addComponent(wdateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameInfo)
                            .addComponent(phoneInfo)
                            .addComponent(emailInfo)
                            .addComponent(addrInfo)
                            .addComponent(shiftInfo)
                            .addComponent(wdateInfo)))
                    .addGroup(profileTabLayout.createSequentialGroup()
                        .addComponent(refreshBtn)
                        .addGap(122, 122, 122)))
                .addContainerGap(533, Short.MAX_VALUE))
        );
        profileTabLayout.setVerticalGroup(
            profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileTabLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(hiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idInfo))
                .addGap(18, 18, 18)
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameInfo))
                .addGap(18, 18, 18)
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneInfo))
                .addGap(18, 18, 18)
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailInfo))
                .addGap(18, 18, 18)
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addrLabel)
                    .addComponent(addrInfo))
                .addGap(18, 18, 18)
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shiftLabel)
                    .addComponent(shiftInfo))
                .addGap(18, 18, 18)
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wdateLabel)
                    .addComponent(wdateInfo))
                .addGap(48, 48, 48)
                .addComponent(refreshBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        home.addTab("Profile", profileTab);

        javax.swing.GroupLayout bookTabLayout = new javax.swing.GroupLayout(bookTab);
        bookTab.setLayout(bookTabLayout);
        bookTabLayout.setHorizontalGroup(
            bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        bookTabLayout.setVerticalGroup(
            bookTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );

        home.addTab("Book", bookTab);

        CustomerIdLabel.setText("CustomerId");

        CustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerIdActionPerformed(evt);
            }
        });

        Displayall.setText("DisplayBill");
        Displayall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayallActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookId", "Amount", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable1);

        jLabel16.setText("StaffId:");

        jLabel17.setText("IDNumber:");

        StaffId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffIdActionPerformed(evt);
            }
        });
        StaffId.setText(""+id_user);

        IdBill.setText(""+(1+BillController.getBillId()));

        CreateBill.setText("CreateBill");
        CreateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBillActionPerformed(evt);
            }
        });

        AddDetailButton.setText("AddDetail");
        AddDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDetailButtonActionPerformed(evt);
            }
        });

        RemoveDetail.setText("RemoveDetail");
        RemoveDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout billTabLayout = new javax.swing.GroupLayout(billTab);
        billTab.setLayout(billTabLayout);
        billTabLayout.setHorizontalGroup(
            billTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billTabLayout.createSequentialGroup()
                        .addComponent(CustomerIdLabel)
                        .addGap(18, 18, 18)
                        .addComponent(CustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Displayall)
                    .addGroup(billTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(billTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(billTabLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(billTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(billTabLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(StaffId, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(billTabLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IdBill))))
                            .addGroup(billTabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CreateBill)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddDetailButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RemoveDetail)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        billTabLayout.setVerticalGroup(
            billTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(billTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerIdLabel)
                    .addComponent(CustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Displayall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(billTabLayout.createSequentialGroup()
                        .addGroup(billTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(StaffId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(billTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(IdBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(184, 184, 184)
                        .addGroup(billTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreateBill)
                            .addComponent(AddDetailButton)
                            .addComponent(RemoveDetail))))
                .addContainerGap(288, Short.MAX_VALUE))
        );

        home.addTab("Bill", billTab);

        javax.swing.GroupLayout reportTabLayout = new javax.swing.GroupLayout(reportTab);
        reportTab.setLayout(reportTabLayout);
        reportTabLayout.setHorizontalGroup(
            reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        reportTabLayout.setVerticalGroup(
            reportTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );

        home.addTab("Report", reportTab);

        cidLabel.setText("ID:");

        cnameLabel.setText("Name:");

        cphoneLabel.setText("Phone:");

        cmailLabel.setText("Email:");

        caddrLabel.setText("Address:");

        cregdateLabel.setText("Register date:");

        expdateLabel.setText("Expired date:");

        membershipLabel.setText("Membership:");

        ccreateBtn.setText("Create");
        ccreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccreateBtnActionPerformed(evt);
            }
        });

        cupdateBtn.setText("Update");
        cupdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupdateBtnActionPerformed(evt);
            }
        });

        cremoveBtn.setText("Remove");
        cremoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cremoveBtnActionPerformed(evt);
            }
        });

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer Name", "Phone"
            }
        ));
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);

        displayaBtn.setText("Display all");
        displayaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayaBtnActionPerformed(evt);
            }
        });

        cSearchBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name", "Phone" }));
        cSearchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSearchBoxActionPerformed(evt);
            }
        });

        cSearchBtn.setText("Search");
        cSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerTabLayout = new javax.swing.GroupLayout(customerTab);
        customerTab.setLayout(customerTabLayout);
        customerTabLayout.setHorizontalGroup(
            customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(customerTabLayout.createSequentialGroup()
                        .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerTabLayout.createSequentialGroup()
                                .addComponent(displayaBtn)
                                .addGap(35, 35, 35)
                                .addComponent(cSearchBtn))
                            .addGroup(customerTabLayout.createSequentialGroup()
                                .addComponent(cSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 259, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerTabLayout.createSequentialGroup()
                        .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(membershipLabel)
                            .addComponent(expdateLabel)
                            .addComponent(cregdateLabel)
                            .addComponent(caddrLabel)
                            .addComponent(cmailLabel)
                            .addComponent(cphoneLabel)
                            .addComponent(cnameLabel)
                            .addComponent(cidLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerTabLayout.createSequentialGroup()
                        .addComponent(ccreateBtn)
                        .addGap(28, 28, 28)))
                .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(customerTabLayout.createSequentialGroup()
                            .addComponent(cupdateBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addComponent(cremoveBtn))
                        .addComponent(cnameField)
                        .addComponent(cphoneField)
                        .addComponent(cmailField)
                        .addComponent(caddrField)
                        .addComponent(cmembershipField))
                    .addComponent(crdateField)
                    .addComponent(cedateField)
                    .addComponent(cidField))
                .addContainerGap())
        );
        customerTabLayout.setVerticalGroup(
            customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerTabLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(customerTabLayout.createSequentialGroup()
                        .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cidLabel)
                            .addComponent(cidField))
                        .addGap(18, 18, 18)
                        .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cnameLabel)
                            .addComponent(cnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cphoneLabel)
                            .addComponent(cphoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmailLabel)
                            .addComponent(cmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caddrLabel)
                            .addComponent(caddrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cregdateLabel)
                            .addComponent(crdateField))
                        .addGap(18, 18, 18)
                        .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(expdateLabel)
                            .addComponent(cedateField))
                        .addGap(18, 18, 18)
                        .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(membershipLabel)
                            .addComponent(cmembershipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cremoveBtn)
                            .addComponent(cupdateBtn)
                            .addComponent(ccreateBtn)))
                    .addGroup(customerTabLayout.createSequentialGroup()
                        .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displayaBtn)
                            .addComponent(cSearchBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(412, Short.MAX_VALUE))
        );

        home.addTab("Customer", customerTab);

        staffTab.setBackground(new java.awt.Color(255, 255, 255));
        staffTab.setToolTipText("");

        ComboBox_search_staff.setBackground(new java.awt.Color(0, 102, 102));
        ComboBox_search_staff.setForeground(new java.awt.Color(255, 255, 255));
        ComboBox_search_staff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name" }));

        Button_Search_staff.setBackground(new java.awt.Color(255, 51, 0));
        Button_Search_staff.setForeground(new java.awt.Color(255, 255, 255));
        Button_Search_staff.setText("Search");
        Button_Search_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Search_staffActionPerformed(evt);
            }
        });

        Table_Staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_StaffMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_Staff);
        if (Table_Staff.getColumnModel().getColumnCount() > 0) {
            Table_Staff.getColumnModel().getColumn(0).setResizable(false);
            Table_Staff.getColumnModel().getColumn(1).setResizable(false);
        }

        image_staff.setText("Image");
        image_staff.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        image_staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                image_staffMouseClicked(evt);
            }
        });

        jLabel2.setText("ID");

        id_staff.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Username");

        jLabel5.setText("Password");

        jLabel6.setText("Name");

        txtname_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtname_staffActionPerformed(evt);
            }
        });

        jLabel1.setText("Phone");

        jLabel7.setText("Email");

        jLabel8.setText("Address");

        jLabel9.setText("Shift count");

        jLabel10.setText("Start work date");

        Button_Add_Staff.setBackground(new java.awt.Color(255, 51, 0));
        Button_Add_Staff.setForeground(new java.awt.Color(255, 255, 255));
        Button_Add_Staff.setText("Save");
        Button_Add_Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Add_StaffActionPerformed(evt);
            }
        });

        Button_Update_staff.setBackground(new java.awt.Color(255, 51, 0));
        Button_Update_staff.setForeground(new java.awt.Color(255, 255, 255));
        Button_Update_staff.setText("Update");
        Button_Update_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Update_staffActionPerformed(evt);
            }
        });

        Button_Delete_staff.setBackground(new java.awt.Color(255, 51, 0));
        Button_Delete_staff.setForeground(new java.awt.Color(255, 255, 255));
        Button_Delete_staff.setText("Delete");
        Button_Delete_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Delete_staffActionPerformed(evt);
            }
        });

        Button_New_Staff.setBackground(new java.awt.Color(255, 51, 0));
        Button_New_Staff.setForeground(new java.awt.Color(255, 255, 255));
        Button_New_Staff.setText("New");
        Button_New_Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_New_StaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout staffTabLayout = new javax.swing.GroupLayout(staffTab);
        staffTab.setLayout(staffTabLayout);
        staffTabLayout.setHorizontalGroup(
            staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffTabLayout.createSequentialGroup()
                        .addComponent(txtsearch_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBox_search_staff, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_Search_staff, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffTabLayout.createSequentialGroup()
                        .addComponent(Button_New_Staff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(Button_Add_Staff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(Button_Update_staff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(Button_Delete_staff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffTabLayout.createSequentialGroup()
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_staff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtusername_staff, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(txtpassword_staff))
                        .addGap(18, 18, 18)
                        .addComponent(image_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffTabLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtname_staff))
                    .addGroup(staffTabLayout.createSequentialGroup()
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtstartworkdate_staff)
                            .addComponent(txtshift_count_staff)))
                    .addGroup(staffTabLayout.createSequentialGroup()
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(staffTabLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtphone_staff))
                            .addGroup(staffTabLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtemail_staff))
                            .addGroup(staffTabLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtaddress_staff)))))
                .addGap(18, 18, 18))
        );
        staffTabLayout.setVerticalGroup(
            staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffTabLayout.createSequentialGroup()
                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(staffTabLayout.createSequentialGroup()
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(staffTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(image_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(staffTabLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_staff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(30, 30, 30)
                                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtusername_staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(26, 26, 26)
                                .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtpassword_staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(28, 28, 28)
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtname_staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(txtphone_staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtemail_staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaddress_staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtshift_count_staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtstartworkdate_staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_Add_Staff)
                            .addComponent(Button_Update_staff)
                            .addComponent(Button_Delete_staff)
                            .addComponent(Button_New_Staff)))
                    .addGroup(staffTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(staffTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsearch_staff)
                            .addComponent(ComboBox_search_staff))
                        .addGap(23, 23, 23)
                        .addComponent(Button_Search_staff)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(246, 246, 246))
        );

        home.addTab("Staff", staffTab);

        adminTab.setBackground(new java.awt.Color(255, 255, 255));

        ComboBox_search_admin.setBackground(new java.awt.Color(0, 102, 102));
        ComboBox_search_admin.setForeground(new java.awt.Color(255, 255, 255));
        ComboBox_search_admin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name" }));

        Button_Search_Admin.setBackground(new java.awt.Color(255, 51, 0));
        Button_Search_Admin.setForeground(new java.awt.Color(255, 255, 255));
        Button_Search_Admin.setText("Search");
        Button_Search_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Search_AdminActionPerformed(evt);
            }
        });

        Table_Admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ));
        Table_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_AdminMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Table_Admin);

        Image_Admin.setText("Image");
        Image_Admin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Image_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Image_AdminMouseClicked(evt);
            }
        });

        jLabel3.setText("ID");

        Label_ID_Admin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Username");

        jLabel12.setText("Password");

        jLabel13.setText("Name");

        jLabel14.setText("Phone");

        jLabel15.setText("Email");

        Button_Add_Admin.setBackground(new java.awt.Color(255, 51, 0));
        Button_Add_Admin.setForeground(new java.awt.Color(255, 255, 255));
        Button_Add_Admin.setText("Save");
        Button_Add_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Add_AdminActionPerformed(evt);
            }
        });

        Button_Update_Admin.setBackground(new java.awt.Color(255, 51, 0));
        Button_Update_Admin.setForeground(new java.awt.Color(255, 255, 255));
        Button_Update_Admin.setText("Update");
        Button_Update_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Update_AdminActionPerformed(evt);
            }
        });

        Button_New_Admin.setBackground(new java.awt.Color(255, 51, 0));
        Button_New_Admin.setForeground(new java.awt.Color(255, 255, 255));
        Button_New_Admin.setText("New");
        Button_New_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_New_AdminActionPerformed(evt);
            }
        });

        Button_Delete_Admin.setBackground(new java.awt.Color(255, 51, 0));
        Button_Delete_Admin.setForeground(new java.awt.Color(255, 255, 255));
        Button_Delete_Admin.setText("Delete");
        Button_Delete_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Delete_AdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminTabLayout = new javax.swing.GroupLayout(adminTab);
        adminTab.setLayout(adminTabLayout);
        adminTabLayout.setHorizontalGroup(
            adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTabLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminTabLayout.createSequentialGroup()
                        .addComponent(txtsearch_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBox_search_admin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_Search_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(72, 72, 72)
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminTabLayout.createSequentialGroup()
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminTabLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminTabLayout.createSequentialGroup()
                                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(29, 29, 29)
                                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword_Admin)
                                    .addComponent(Label_ID_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtUsername_Admin))
                                .addGap(32, 32, 32)))
                        .addComponent(Image_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminTabLayout.createSequentialGroup()
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(47, 47, 47)
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName_Admin)
                            .addComponent(txtPhone_Admin)
                            .addComponent(txtEmail_Admin)))
                    .addGroup(adminTabLayout.createSequentialGroup()
                        .addComponent(Button_New_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                        .addGap(48, 48, 48)
                        .addComponent(Button_Add_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                        .addGap(52, 52, 52)
                        .addComponent(Button_Update_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52)
                        .addComponent(Button_Delete_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        adminTabLayout.setVerticalGroup(
            adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTabLayout.createSequentialGroup()
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(adminTabLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsearch_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_search_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(Button_Search_Admin)
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminTabLayout.createSequentialGroup()
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(adminTabLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_ID_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(54, 54, 54)
                                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtUsername_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPassword_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addGroup(adminTabLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(Image_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtName_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtPhone_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(txtEmail_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_Add_Admin)
                            .addComponent(Button_New_Admin)
                            .addComponent(Button_Update_Admin)
                            .addComponent(Button_Delete_Admin))))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        home.addTab("Admin", adminTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        this.dispose();
        LoginOption.getInstance().setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        reloadProfile();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void ccreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccreateBtnActionPerformed
        AddCustomer ac=new AddCustomer();
        ac.setVisible(true);
    }//GEN-LAST:event_ccreateBtnActionPerformed

    private void displayaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayaBtnActionPerformed
        CustomerController.displayAllCustomer(customerTable);
    }//GEN-LAST:event_displayaBtnActionPerformed

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        int d = (int)customerTable.getValueAt(customerTable.getSelectedRow(), 0);
        CustomerController.getCustomerByID(d, cidField, cnameField, cphoneField, cmailField, caddrField,
                crdateField, cedateField, cmembershipField);
    }//GEN-LAST:event_customerTableMouseClicked

    private void cremoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cremoveBtnActionPerformed
        int a = customerTable.getSelectedRow();
        if (a == -1){
            JOptionPane.showMessageDialog(null, "You must choose a customer");
        } else {
            a = (int)customerTable.getValueAt(customerTable.getSelectedRow(), 0);
            CustomerController.removeCustomer(a);
            //Load lai toan bo bang
            CustomerController.displayAllCustomer(customerTable);
            // Xoa cac truong thong tin
            cidField.setText(null);
            cnameField.setText(null);
            cphoneField.setText(null);
            cmailField.setText(null);
            caddrField.setText(null);
            crdateField.setText(null);
            cedateField.setText(null);
            cmembershipField.setText(null);
        }  
    }//GEN-LAST:event_cremoveBtnActionPerformed

    private void cupdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupdateBtnActionPerformed
        if (cidField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please choose a customer from customer table");
        } else {
            CustomerController.updateCustomer(cidField, cnameField, cphoneField, cmailField, caddrField,
                crdateField, cedateField, cmembershipField);
            //Load lai toan bo bang
            CustomerController.displayAllCustomer(customerTable);
        }
    }//GEN-LAST:event_cupdateBtnActionPerformed

    private void cSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSearchBtnActionPerformed
        String a =(String) cSearchBox.getSelectedItem();
        String b = cSearchField.getText();
        CustomerController.searchCustomer(a, b, customerTable);
    }//GEN-LAST:event_cSearchBtnActionPerformed

    private void cSearchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSearchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSearchBoxActionPerformed

    private void Table_StaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_StaffMouseClicked
        
        stf.getStaffByID(Table_Staff, txtname_staff, txtphone_staff, txtemail_staff, txtaddress_staff, txtshift_count_staff, 
                txtusername_staff, txtpassword_staff, txtstartworkdate_staff, image_staff, id_staff);
    }//GEN-LAST:event_Table_StaffMouseClicked

    private void image_staffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_image_staffMouseClicked
        ImagePath = Controller.StaffController.getImageStaff(image_staff, ImagePath);
    }//GEN-LAST:event_image_staffMouseClicked

    private void Button_Search_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Search_staffActionPerformed
        stf.SearchStaff(Table_Staff, ComboBox_search_staff, txtsearch_staff);
    }//GEN-LAST:event_Button_Search_staffActionPerformed

    private void Button_Update_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Update_staffActionPerformed
        stf.UpdateStaff(txtname_staff, txtphone_staff, txtemail_staff, txtaddress_staff, txtshift_count_staff, 
                txtstartworkdate_staff, txtusername_staff, txtpassword_staff, image_staff, id_staff, ImagePath);
        stf.DisplayAllStaff(Table_Staff);
    }//GEN-LAST:event_Button_Update_staffActionPerformed

    private void Button_Add_StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Add_StaffActionPerformed
        stf.AddStaff(txtname_staff, txtphone_staff, txtemail_staff, txtaddress_staff, txtshift_count_staff, 
                txtstartworkdate_staff, txtusername_staff, txtpassword_staff, image_staff, ImagePath);
        stf.DisplayAllStaff(Table_Staff);
    }//GEN-LAST:event_Button_Add_StaffActionPerformed

    private void Button_New_StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_New_StaffActionPerformed
        stf.New(txtname_staff, txtphone_staff, txtemail_staff, txtaddress_staff, txtshift_count_staff, 
                txtstartworkdate_staff, txtusername_staff, txtpassword_staff, image_staff, id_staff);
    }//GEN-LAST:event_Button_New_StaffActionPerformed

    private void Button_Delete_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Delete_staffActionPerformed
        stf.DeleteStaff(Table_Staff);
        stf.DisplayAllStaff(Table_Staff);
    }//GEN-LAST:event_Button_Delete_staffActionPerformed

    private void txtname_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtname_staffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtname_staffActionPerformed

    private void Button_Search_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Search_AdminActionPerformed
        ad.SearchAdmin(Table_Admin, ComboBox_search_admin, txtsearch_admin);
    }//GEN-LAST:event_Button_Search_AdminActionPerformed

    private void Table_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_AdminMouseClicked
        ad.getAdminByID(Table_Admin, txtName_Admin, txtPhone_Admin, txtEmail_Admin, txtUsername_Admin, 
                txtPassword_Admin, Image_Admin, Label_ID_Admin);
    }//GEN-LAST:event_Table_AdminMouseClicked

    private void Image_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Image_AdminMouseClicked
        ImagePath = Controller.AdminController.getImageAdmin(Image_Admin, ImagePath);
    }//GEN-LAST:event_Image_AdminMouseClicked

    private void Button_Update_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Update_AdminActionPerformed
        ad.UpdateAdmin(txtName_Admin, txtPhone_Admin, txtEmail_Admin, txtUsername_Admin, 
                txtPassword_Admin, Image_Admin, Label_ID_Admin, ImagePath);
        ad.DisplayAllAdmin(Table_Admin);
    }//GEN-LAST:event_Button_Update_AdminActionPerformed

    private void Button_New_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_New_AdminActionPerformed
        ad.New(txtName_Admin, txtPhone_Admin, txtEmail_Admin, txtUsername_Admin, 
                txtPassword_Admin, Image_Admin, Label_ID_Admin);
    }//GEN-LAST:event_Button_New_AdminActionPerformed

    private void Button_Add_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Add_AdminActionPerformed
        ad.AddAdmin(txtName_Admin, txtPhone_Admin, txtEmail_Admin, txtUsername_Admin, 
                txtPassword_Admin, Image_Admin, ImagePath);
        ad.DisplayAllAdmin(Table_Admin);
    }//GEN-LAST:event_Button_Add_AdminActionPerformed

    private void Button_Delete_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Delete_AdminActionPerformed
        ad.DeleteAdmin(Table_Admin);
        ad.DisplayAllAdmin(Table_Admin);
    }//GEN-LAST:event_Button_Delete_AdminActionPerformed

    private void CustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerIdActionPerformed

    private void DisplayallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayallActionPerformed
        // TODO add your handling code here:
        new DisplayBill().setVisible(true);
    }//GEN-LAST:event_DisplayallActionPerformed

    private void StaffIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffIdActionPerformed

    private void CreateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBillActionPerformed
        // TODO add your handling code here:
        BillController.addBill(CustomerId,StaffId.getText(),totalprice);
        new PrintBill().setVisible(true); 
        totalprice=0;
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        IdBill.setText(""+(1+BillController.getBillId()));
        
    }//GEN-LAST:event_CreateBillActionPerformed

    private void AddDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDetailButtonActionPerformed
        // TODO add your handling code here:
        AddBillDetail a = new AddBillDetail();
        a.setVisible(true);
        a.addWindowListener(new java.awt.event.WindowAdapter(){
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                String bookid = a.getbookid();
                String amount = a.getamount();
                String price = BillController.getPrice(bookid);
                if(price == null){
                JOptionPane.showMessageDialog(null, "invalid bookid");
                }
                else{
                DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
                m.addRow(new Object[] {bookid,amount,Integer.parseInt(amount)*Integer.parseInt(price)});                
                
                totalprice = totalprice + Integer.parseInt(amount)*Integer.parseInt(price);
                
                System.out.println(totalprice);
//                System.out.println(a.getamount());
                }
                
                a.setVisible(false);
            }
            
        });
    }//GEN-LAST:event_AddDetailButtonActionPerformed

    private void RemoveDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveDetailActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        int[] rows = jTable1.getSelectedRows();
        for(int i=0;i<rows.length;i++){
            totalprice -= Integer.parseInt(""+jTable1.getValueAt(rows[i]-i, 2));
            model.removeRow(rows[i]-i);
        }
    }//GEN-LAST:event_RemoveDetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDetailButton;
    private javax.swing.JButton Button_Add_Admin;
    private javax.swing.JButton Button_Add_Staff;
    private javax.swing.JButton Button_Delete_Admin;
    private javax.swing.JButton Button_Delete_staff;
    private javax.swing.JButton Button_New_Admin;
    private javax.swing.JButton Button_New_Staff;
    private javax.swing.JButton Button_Search_Admin;
    private javax.swing.JButton Button_Search_staff;
    private javax.swing.JButton Button_Update_Admin;
    private javax.swing.JButton Button_Update_staff;
    private javax.swing.JComboBox<String> ComboBox_search_admin;
    private javax.swing.JComboBox<String> ComboBox_search_staff;
    private javax.swing.JButton CreateBill;
    private javax.swing.JTextField CustomerId;
    private javax.swing.JLabel CustomerIdLabel;
    private javax.swing.JButton Displayall;
    private javax.swing.JTextField IdBill;
    private javax.swing.JLabel Image_Admin;
    private javax.swing.JLabel Label_ID_Admin;
    private javax.swing.JButton RemoveDetail;
    private javax.swing.JTextField StaffId;
    private javax.swing.JTable Table_Admin;
    private javax.swing.JTable Table_Staff;
    private javax.swing.JLabel addrInfo;
    private javax.swing.JLabel addrLabel;
    private javax.swing.JPanel adminTab;
    private javax.swing.JPanel billTab;
    private javax.swing.JPanel bookTab;
    private javax.swing.JComboBox<String> cSearchBox;
    private javax.swing.JButton cSearchBtn;
    private javax.swing.JTextField cSearchField;
    private javax.swing.JTextField caddrField;
    private javax.swing.JLabel caddrLabel;
    private javax.swing.JButton ccreateBtn;
    private javax.swing.JLabel cedateField;
    private javax.swing.JLabel cidField;
    private javax.swing.JLabel cidLabel;
    private javax.swing.JTextField cmailField;
    private javax.swing.JLabel cmailLabel;
    private javax.swing.JTextField cmembershipField;
    private javax.swing.JTextField cnameField;
    private javax.swing.JLabel cnameLabel;
    private javax.swing.JTextField cphoneField;
    private javax.swing.JLabel cphoneLabel;
    private javax.swing.JLabel crdateField;
    private javax.swing.JLabel cregdateLabel;
    private javax.swing.JButton cremoveBtn;
    private javax.swing.JButton cupdateBtn;
    private javax.swing.JPanel customerTab;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton displayaBtn;
    private javax.swing.JLabel emailInfo;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel expdateLabel;
    private javax.swing.JLabel hiLabel;
    private javax.swing.JTabbedPane home;
    private javax.swing.JLabel idInfo;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel id_staff;
    private javax.swing.JLabel image_staff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel membershipLabel;
    private javax.swing.JLabel nameInfo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel phoneInfo;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JPanel profileTab;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JPanel reportTab;
    private javax.swing.JLabel shiftInfo;
    private javax.swing.JLabel shiftLabel;
    private javax.swing.JPanel staffTab;
    private javax.swing.JTextField txtEmail_Admin;
    private javax.swing.JTextField txtName_Admin;
    private javax.swing.JTextField txtPassword_Admin;
    private javax.swing.JTextField txtPhone_Admin;
    private javax.swing.JTextField txtUsername_Admin;
    private javax.swing.JTextField txtaddress_staff;
    private javax.swing.JTextField txtemail_staff;
    private javax.swing.JTextField txtname_staff;
    private javax.swing.JTextField txtpassword_staff;
    private javax.swing.JTextField txtphone_staff;
    private javax.swing.JTextField txtsearch_admin;
    private javax.swing.JTextField txtsearch_staff;
    private javax.swing.JTextField txtshift_count_staff;
    private javax.swing.JTextField txtstartworkdate_staff;
    private javax.swing.JTextField txtusername_staff;
    private javax.swing.JLabel wdateInfo;
    private javax.swing.JLabel wdateLabel;
    // End of variables declaration//GEN-END:variables
}
